name: Exemple By ENA

on:
  push:
    branches:
      - ena-test
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t ena .
      - name: push
        run: docker push 047760725625.dkr.ecr.us-east-1.amazonaws.com/fgh-demo:latest