on:
  push:
    branches:
      - main    
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS ECR credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ENA_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ENA_ECR_ACCESS_KEY_SECRET }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: push Docker image
        run: |
          docker build -f Dockerfile \
            -t ${REPO}:STG-${GITHUB_SHA:1:7} .
          docker tag ${REPO}:STG-${GITHUB_SHA:1:7} ${REPO}:master
          docker push ${REPO}:master
          
          
          
          
